# Generated by Django 3.2.8 on 2021-10-11 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_hostel_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owner',
            name='residence',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
